[env:HTIT-WB32LAF]
extends = common
board = heltec_wifi_lora_32_V3
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_HTIT_WB32LAF
    -DAXLORA_HAS_OLED
    -Ivariants/HTIT-WB32LAF